export const createConstants = {
  heading: 'Create an offer',
  title: 'Title',
  titlePlaceholder: 'Luxury villa with pool',
  titleInvalidText: 'Title is required.',
  location: 'Location',
  locationPlaceholder: 'USA, New York 1234 AU',
  locationInvalidText: 'Location is required.',
  quadrature: 'Quadrature',
  quadraturePlaceholder: '250.25',
  quadratureInvalidText: 'Quadrature is required.',
  floors: 'Floors',
  floorsPlaceholder: '3',
  floorsInvalidText: 'Floors is required.',
  imageUrl: 'Image Link',
  imageUrlPlaceholder: 'https://...',
  imageUrlInvalidText: 'Image link is required.',
  price: 'Price',
  pricePlaceholder: '1000000.00',
  priceInvalidText: 'Price is required.',
  information: 'Information about the offer',
  informationInvalidText: 'Information must be at least 20 characters long.',
  btnText: 'Create',
};
