export const editConstants = {
  heading: 'Edit an offer',
  title: 'Title',
  titleInvalidText: 'Title is required.',
  location: 'Location',
  locationInvalidText: 'Location is required.',
  quadrature: 'Quadrature',
  quadratureInvalidText: 'Quadrature is required.',
  floors: 'Floors',
  floorsInvalidText: 'Floors is required.',
  imageUrl: 'Image Link',
  imageUrlInvalidText: 'Image link is required.',
  price: 'Price',
  priceInvalidText: 'Price is required.',
  information: 'Information about the offer',
  informationInvalidText: 'Information must be at least 20 characters long.',
  btnText: 'Edit',
};
