export const registerConstants = {
  heading: 'Register',
  fullName: 'Full name',
  fullNamePlaceholder: 'Dimitar Mitev',
  fullNameInvalidText: 'Full Name is required.',
  username: 'Username',
  usernamePlaceholder: 'dmitev',
  usernameInvalidText: 'Username is required.',
  email: 'Email',
  emailPlaceholder: 'd.mitev@gmail.com',
  emailInvalidText: 'Email is required.',
  phone: 'Phone Number',
  phonePlaceholder: '0999999999',
  phoneInvalidText: 'Phone number must be at least 10 characters long.',
  password: 'Password',
  passwordPlaceholder: '******',
  passwordInvalidText: 'Password must be at least 6 characters long.',
  rePassword: 'Repeat password',
  rePasswordPlaceholder: '******',
  rePasswordInvalidText: 'Passwords mismatch.',
  termsText: 'By creating an account you agree to our',
  termsTextAnch: 'Terms & Privacy.',
  btnText: 'Register',
  account: 'Have already an account?',
  btnAccount: 'Login here',
};
